config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :orders
  resources :line_items
  resources :carts
  root 'home#index'
  resources :maillots
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/maillot.rb
class Maillot < ApplicationRecord
	has_many :line_items, dependent: :nullify

	validates :title, :description, :image_url, presence: true
	validates :price, numericality: { greater_than_or_equal_to: 1 }
	validates :title, uniqueness: { case_sensitive: false }
	validates :image_url,
		format: {
			with: /\.(jpg|png|gif)\z/i,
			message: "doit être au format jpg, png ou gif"
		},
		allow_blank: true
end

app/controllers/maillots_controller.rb
class MaillotsController < ApplicationController
  before_action :set_maillot, only: [:show, :edit, :update, :destroy]

  # GET /maillots
  # GET /maillots.json
  def index
    @maillots = Maillot.all
  end

  # GET /maillots/1
  # GET /maillots/1.json
  def show
  end

  # GET /maillots/new
  def new
    @maillot = Maillot.new
  end

  # GET /maillots/1/edit
  def edit
  end

  # POST /maillots
  # POST /maillots.json
  def create
    @maillot = Maillot.new(maillot_params)

    respond_to do |format|
      if @maillot.save
        format.html { redirect_to @maillot, notice: 'Maillot was successfully created.' }
        format.json { render :show, status: :created, location: @maillot }
      else
        format.html { render :new }
        format.json { render json: @maillot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /maillots/1
  # PATCH/PUT /maillots/1.json
  def update
    respond_to do |format|
      if @maillot.update(maillot_params)
        format.html { redirect_to @maillot, notice: 'Maillot was successfully updated.' }
        format.json { render :show, status: :ok, location: @maillot }
      else
        format.html { render :edit }
        format.json { render json: @maillot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /maillots/1
  # DELETE /maillots/1.json
  def destroy
    @maillot.destroy
    respond_to do |format|
      format.html { redirect_to maillots_url, notice: 'Maillot was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_maillot
      @maillot = Maillot.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def maillot_params
      params.require(:maillot).permit(:title, :description, :price, :image_url)
    end
end

app/helpers/maillots_helper.rb
module MaillotsHelper
end

app/views/maillots/_form.html.erb
<%= form_with(model: maillot, local: true) do |form| %>
  <% if maillot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(maillot.errors.count, "error") %> prohibited this maillot from being saved:</h2>

      <ul>
      <% maillot.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, cols: 60, rows: 10 %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :image_url %>
    <%= form.text_field :image_url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/maillots/edit.html.erb
<h1>Editing Maillot</h1>

<%= render 'form', maillot: @maillot %>

<%= link_to 'Show', @maillot %> |
<%= link_to 'Back', maillots_path %>

app/views/maillots/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="text-center text-primary">Maillots</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Price</th>
      <th>Image</th>
      <th class="text-center">Action</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @maillots.each do |maillot| %>
      <tr>
        <td><%= maillot.title %></td>
        <td><%= truncate strip_tags(maillot.description), length: 80 %></td>
        <td><%= number_to_currency maillot.price, unit: "€", separator: ",", format: "%n%u" %></td>
        <td><%= image_tag maillot.image_url, width: 60 %></td>
        <td><%= link_to 'Show', maillot, class: "btn btn-primary" %></td>
        <td><%= link_to 'Edit', edit_maillot_path(maillot), class: "btn btn-success" %></td>
        <td><%= link_to 'Destroy', maillot, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Maillot', new_maillot_path %>

app/views/maillots/new.html.erb
<h1>New Maillot</h1>

<%= render 'form', maillot: @maillot %>

<%= link_to 'Back', maillots_path %>

app/views/maillots/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @maillot.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= raw @maillot.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @maillot.price %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @maillot.image_url %>
</p>

<%= link_to 'Edit', edit_maillot_path(@maillot) %> |
<%= link_to 'Back', maillots_path %>